### ISSUE TITLE
Open Google search in user's favorite browser; do not force Chrome

### ISSUE THREAD

**Issue by austinjdean** [austinjdean/pls#2]
This can probably be implemented in a couple ways:
- config file for user to specify browser
- use $BROWSER environment variable

**Comment by RyanYoung25** [comment]
I like the environment variable idea. But what are you ideas for making it available? Sourcing a config script in the bashrc? 

Additionally for the use of other browsers are we just looking at firefox and chrome for now? I was thinking we should be able to pass in flags like -f for firefox and -c for chrome to specify regardless of the default.

**Comment by austinjdean** [comment]
As of 091cb9d8df868362f30c3a328dc633061a797c1f, -c and -f flags are supported. If none are specified, go will use the system default browser with `xdg-open`.
