### ISSUE TITLE
Makefile or install/uninstall scripts

### ISSUE THREAD

**Issue by austinjdean** [austinjdean/pls#3]
For assisting with installation and removal, we could use either a makefile or roll our own install scripts. Using Make centralizes and streamlines the install/uninstall process, building on already-structurally sound software. I'm all ears on which method we should use though.

**Comment by RyanYoung25** [comment]
If you really want to use a make system I would recommend ant just because I like it better than make. But I would prefer a setup.sh script that handles the configuration in just a plain bash script to either of them.

**Comment by austinjdean** [comment]
I did a little research on ant, and already like it better than make. Not that this will get to be a very big project, but I generally prefer the practice of scalability, and as such I prefer a more facilitated installation process.

But nonetheless, go ahead and checkout a branch that uses shell scripts for install and uninstall and push it. We can try out both methods and decide on one after seeing them both in action.

**Comment by austinjdean** [comment]
Installing and cleaning with ant is implemented on master branch; awaiting comparison to Ryan's scripts to choose an installation method.

**Comment by austinjdean** [comment]
We seem to be going with ant here, so I'll close this for now. Still open to using Ryan's scripts though.
